### ISSUE TITLE
PICO_SDK_PATH not set

### ISSUE THREAD

**Issue by tamberg** [NessieCircuits/Riotee_ProbeFirmware#4]
Hi, on MacOS I get the following error. Consider including the necessary steps to set PICO_SDK_PATH, etc. in the README. Thanks, Thomas

$ cmake ..
CMake Error at pico_sdk_import.cmake:55 (message):
  SDK location was not specified.  Please set PICO_SDK_PATH or set
  PICO_SDK_FETCH_FROM_GIT to on to fetch from git.
Call Stack (most recent call first):
  CMakeLists.txt:3 (include)

**Comment by geissdoerfer** [comment]
`PICO_SDK_PATH` should be set during the installation of the Pico SDK. The `pico_setup.sh` script should do this for you. Do you want to report the issue there?

**Comment by tamberg** [comment]
Oops, just notice 

> Follow the [official instructions](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf) to install and setup the Pico SDK.

in https://github.com/NessieCircuits/Riotee_ProbeSoftware#building-the-firmware

Thanks!
